CREATE TABLE User (
	ID INTEGER NOT NULL PRIMARY KEY,
	Name TEXT NOT NULL
);

CREATE TABLE Bundle (
	ID TEXT NOT NULL PRIMARY KEY
);

CREATE TABLE Token (
	ID TEXT NOT NULL PRIMARY KEY,
	UserID INTEGER NOT NULL,
	BundleID TEXT NOT NULL,
	FOREIGN KEY (UserID) REFERENCES User(ID),
	FOREIGN KEY (BundleID) REFERENCES Bundle(ID)
);

CREATE TABLE Session (
	ID INTEGER NOT NULL PRIMARY KEY
);

CREATE TABLE SessionRelationship (
	UserID INTEGER NOT NULL,
	SessionID INTEGER NOT NULL,
	FOREIGN KEY (UserID) REFERENCES User(ID),
	FOREIGN KEY (SessionID) REFERENCES Session(ID),
	UNIQUE (UserID, SessionID)
);
